import os
os.system("pip install subprocess.run")
os.system("pip install requests")
os.system("pip install colorama")
os.system("pip install urllib3")
os.system("pip install hashlib")
os.system("sudo apt-get install nmap")
os.system("sudo apt-get install wpscan")
os.system("sudo apt-get install dirb")
os.system("sudo apt-get install medusa")
os.system("sudo apt-get install weevely")
os.system("sudo apt-get install sqlmap")
os.system("sudo apt-get install nikto")
os.system("sudo apt-get install figlet")
os.system("sudo apt-get install urlcrazy")
os.system("sudo apt-get install dmitry")
os.system("sudo apt-get install uniscan")
os.system("sudo apt-get install urlcrazy")
os.system("sudo apt-get install whatweb")
print("__________________________________________")


